from enum import IntEnum


class StatusCodes(IntEnum):
    ENTITY_CREATED = 100
    ENTITY_DESTROYED = 101
    ENTITY_ACTIVE = 102
    ENTITY_INACTIVE = 103

    COMPONENT_ADDED = 200
    COMPONENT_REMOVED = 201
    COMPONENT_UPDATED = 202
    COMPONENT_NOT_FOUND = 203

    SYSTEM_REGISTERED = 300
    SYSTEM_UNREGISTERED = 301
    SYSTEM_STARTED = 302
    SYSTEM_STOPPED = 303
    SYSTEM_ERROR = 304

    QUERY_SUCCESS = 400
    QUERY_NO_RESULTS = 401
    QUERY_INVALID = 402

    SUCCESS = 0
    FAILURE = -1
    PENDING = 1
    NOT_INITIALIZED = 2
