from pyecs.common.Types import Entity as Entity, UUID4 as UUID4
from pyecs.helpers.Statuses import StatusCodes as StatusCodes
from typing import Literal

class EntityManager:
    alive_entities: set[UUID4]
    def __init__(self) -> None: ...
    def create_entity(self) -> tuple[Literal[StatusCodes.ENTITY_CREATED], Entity] | Literal[StatusCodes.FAILURE]: ...
    def destroy_entity(self, entity: Entity) -> Literal[StatusCodes.ENTITY_DESTROYED, StatusCodes.FAILURE]: ...
    def is_alive(self, entity: Entity) -> bool: ...
