from pyecs.common.Types import UUID4 as UUID4
from pyecs.helpers.Statuses import StatusCodes as StatusCodes
from pyecs.processing.System import System as System
from typing import Literal

class SystemManager:
    systems: list[System]
    system_to_id: dict[System, UUID4]
    id_to_system: dict[UUID4, System]
    def __init__(self) -> None: ...
    def register_system(self, system: System) -> tuple[Literal[StatusCodes.SYSTEM_REGISTERED], System] | Literal[StatusCodes.FAILURE]: ...
    def unregister_system(self, id: UUID4) -> Literal[StatusCodes.SYSTEM_UNREGISTERED, StatusCodes.FAILURE]: ...
    def remove_system(self, system: System) -> Literal[StatusCodes.SYSTEM_UNREGISTERED, StatusCodes.FAILURE]: ...
    def update_all(self, world, dt: float) -> None: ...
