coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "docker/**/*"
  - "docs/**/*"
  - "*.md"

github_checks:
  annotations: true