from pyecs.core.World import ECSWorld as ECSWorld
from typing import Protocol

class System(Protocol):
    @property
    def required_components(self) -> set[type]: ...
    def init(self, world) -> None: ...
    def update(self, world, dt: float) -> None: ...
    def cleanup(self, world) -> None: ...
