from collections.abc import Callable as Callable
from pyecs.exceptions import ComponentNotFoundError as ComponentNotFoundError, EntityNotFoundError as EntityNotFoundError, OperationFailedError as OperationFailedError
from pyecs.helpers.Statuses import StatusCodes as StatusCodes

def generate_unsafe[**P, R](exception_type: type[Exception] = ..., error_message: str | None = None) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
def process_unsafe_methods[C](cls) -> type[C]: ...
def auto_unsafe[C](cls) -> type[C]: ...
