flowchart TD
    Start([add_component called with entity and component]) --> CheckEntity{Entity in entity_to_archetype?}
    
    CheckEntity -->|No| ReturnFailure[Return FAILURE]
    CheckEntity -->|Yes| GetMask[Get current archetype mask]
    
    GetMask --> GetArchetype[Get current archetype from mask]
    GetArchetype --> CheckComponentType{Component type in mask?}
    
    CheckComponentType -->|No| CreateNewMask[Create new mask with component type]
    CheckComponentType -->|Yes| GetEntityIndex[Get entity index in archetype]
    
    CreateNewMask --> GetComponents[Get all entity components]
    GetComponents --> AppendComponent[Append new component to list]
    AppendComponent --> MoveEntity[Call move_entity_to_archetype with new mask]
    MoveEntity --> ReturnAdded[Return COMPONENT_ADDED]
    
    GetEntityIndex --> UpdateComponent[Update component at entity index]
    UpdateComponent --> ReturnUpdated[Return COMPONENT_UPDATED]
    
    ReturnFailure --> End1([End])
    ReturnAdded --> End2([End])
    ReturnUpdated --> End3([End])