from pyecs.common.Types import Component as Component, Entity as Entity
from pyecs.containers.ComponentStorage import ComponentStorage as ComponentStorage
from pyecs.core.World import ECSWorld as ECSWorld
from pyecs.helpers.Deprecation import warn_deprecated as warn_deprecated
from typing import overload

class Query:
    def __init__(self) -> None: ...
    def with_components(self, *types: type[Component]) -> Query: ...
    def without_components(self, *types: type[Component]) -> Query: ...
    @overload
    def execute(self, storage_or_world: ComponentStorage) -> list[Entity]: ...
    @overload
    def execute(self, storage_or_world: ECSWorld) -> list[Entity]: ...
