from collections.abc import Iterator
from pyecs.common.Types import Component as Component, Entity as Entity, SuccessOrFailure as SuccessOrFailure, UUID4 as UUID4
from pyecs.helpers.Statuses import StatusCodes as StatusCodes
from typing import Literal

class Archetype:
    entities: list[UUID4]
    entity_indices: dict[UUID4, int]
    components: dict[type, list[Component]]
    def __init__(self) -> None: ...
    def add_entity(self, entity: Entity, components: list[Component]) -> SuccessOrFailure: ...
    def remove_entity(self, entity: Entity) -> SuccessOrFailure: ...
    def get_component(self, entity: Entity, component_type: type[Component]) -> Component | Literal[StatusCodes.FAILURE]: ...
    def iter_entities(self) -> Iterator[Entity]: ...
    def iter_components(self, component_type: type) -> Iterator[Component]: ...
