flowchart TD
    Start([remove_entity called with entity]) --> CheckExists{Entity in entity_indices dict?}
    
    CheckExists -->|No| ReturnFailure[Return FAILURE]
    CheckExists -->|Yes| GetIndex[Get entity_index from dict - O1 lookup]
    
    GetIndex --> CheckLast{Is entity_index == last_index?}
    
    CheckLast -->|No| SwapWithLast[Swap entity with last entity in lists]
    SwapWithLast --> UpdateLastEntityIndex[Update last entity's index in dict]
    UpdateLastEntityIndex --> SwapComponents[Swap components in all component lists]
    SwapComponents --> RemoveLast
    
    CheckLast -->|Yes| RemoveLast[Pop last entity from entities list]
    RemoveLast --> RemoveFromDict[Delete entity from entity_indices dict]
    RemoveFromDict --> PopComponents[Pop last element from all component lists]
    
    PopComponents --> ReturnSuccess[Return SUCCESS]
    
    ReturnFailure --> End1([End])
    ReturnSuccess --> End2([End])